# Docker Compose specification
# version attribute removed as it's now obsolete
services:
  postgres:
    container_name: postgres-sql
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vehicle_tracker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-vehicle-tracker
    restart: unless-stopped

  vehicle-tracker:
    container_name: vehicle-tracker-app
    build:
      context: .
      dockerfile: Dockerfile
    image: vehicle_tracker:1.0.0
    environment:
      DB_USERNAME: username
      DB_PASSWORD: password
    ports:
      - "8900:8900"
    networks:
      - spring-vehicle-tracker
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  spring-vehicle-tracker:
    driver: bridge

volumes:
  postgres-data: