spring:
  application:
    name: Vehicle_Tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle_tracker
    username: postgres
    password: 1234


  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8900


logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG


management:
  endpoint:
    health:
      show-details: always

application:
  security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days


